version: "3"
volumes:
  postgres-data:
services:
  main:
    image: balance-app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - ./logs:/app/logs
    depends_on:
      - balance-db
    environment:
      WAIT_HOSTS: balance-db:5432
  balance-db:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql
    env_file:
      - ./env/db.env
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G


