log_level = "debug"
log_path = "./logs/"
bind_addr = ":8080"

currency_api = "http://www.cbr-xml-daily.ru/latest.js"

[server]
database_url = "host=balance-db port=5432 user=intern password=1111 dbname=balance_db sslmode=disable"
